"""
ScreenerIII Configuration Package
"""

from .settings import (
    # Application settings
    APP_NAME,
    APP_VERSION,
    DEBUG,
    BASE_DIR,

    # Database configuration
    DATABASE_TYPE,
    DATABASE_URL,
    DATABASE_CONFIG,
    POSTGRES_CONFIG,
    TIMESCALEDB_CONFIG,
    ACTIVE_DATABASE_CONFIG,

    # API settings
    OANDA_API_KEY,
    OANDA_ACCOUNT_ID,
    OANDA_ENVIRONMENT,
    OANDA_API_URLS,

    # Data settings
    DATA_RETENTION_DAYS,
    CANDLE_GRANULARITY,
    CANDLE_COUNT,

    # Signal settings
    SIGNAL_CONFIDENCE_THRESHOLD,
    MIN_RISK_REWARD_RATIO,

    # Display settings
    REFRESH_RATE,
    DECIMAL_PLACES,
    PERCENTAGE_DECIMAL_PLACES,

    # Logging
    LOG_LEVEL,
    LOGGING_CONFIG,

    # Colors
    COLORS,

    # Alert settings
    ENABLE_ALERTS,
    ALERT_COOLDOWN,
)

__all__ = [
    "APP_NAME",
    "APP_VERSION",
    "DEBUG",
    "BASE_DIR",
    "DATABASE_TYPE",
    "DATABASE_URL",
    "DATABASE_CONFIG",
    "POSTGRES_CONFIG",
    "TIMESCALEDB_CONFIG",
    "ACTIVE_DATABASE_CONFIG",
    "OANDA_API_KEY",
    "OANDA_ACCOUNT_ID",
    "OANDA_ENVIRONMENT",
    "OANDA_API_URLS",
    "DATA_RETENTION_DAYS",
    "CANDLE_GRANULARITY",
    "CANDLE_COUNT",
    "SIGNAL_CONFIDENCE_THRESHOLD",
    "MIN_RISK_REWARD_RATIO",
    "REFRESH_RATE",
    "DECIMAL_PLACES",
    "PERCENTAGE_DECIMAL_PLACES",
    "LOG_LEVEL",
    "LOGGING_CONFIG",
    "COLORS",
    "ENABLE_ALERTS",
    "ALERT_COOLDOWN",
]
