"""
Utils package for ScreenerIII application.

This package provides utility modules for validation and helper functions.
"""

from .validators import (
    ValidationError,
    validate_market_symbol,
    validate_numeric_range,
    validate_percentage,
    validate_api_response,
    validate_config,
    validate_date_string,
    validate_email,
    validate_url,
    validate_list_not_empty,
    validate_file_path,
    validate_timeframe,
)

from .helpers import (
    get_current_timestamp,
    get_current_datetime,
    timestamp_to_datetime,
    datetime_to_timestamp,
    format_datetime,
    parse_datetime,
    get_date_range,
    days_between,
    add_business_days,
    calculate_percentage_change,
    calculate_average,
    calculate_moving_average,
    safe_divide,
    clamp,
    round_to_precision,
    parse_decimal,
    flatten_dict,
    unflatten_dict,
    deep_merge,
    filter_dict,
    remove_none_values,
    chunk_list,
    deduplicate_list,
    truncate_string,
    sanitize_filename,
    generate_hash,
    safe_json_loads,
    safe_json_dumps,
    pretty_json,
    retry,
    timer,
    memoize,
    get_nested_value,
    set_nested_value,
    ensure_list,
)

__all__ = [
    # Validators
    'ValidationError',
    'validate_market_symbol',
    'validate_numeric_range',
    'validate_percentage',
    'validate_api_response',
    'validate_config',
    'validate_date_string',
    'validate_email',
    'validate_url',
    'validate_list_not_empty',
    'validate_file_path',
    'validate_timeframe',
    # Helpers
    'get_current_timestamp',
    'get_current_datetime',
    'timestamp_to_datetime',
    'datetime_to_timestamp',
    'format_datetime',
    'parse_datetime',
    'get_date_range',
    'days_between',
    'add_business_days',
    'calculate_percentage_change',
    'calculate_average',
    'calculate_moving_average',
    'safe_divide',
    'clamp',
    'round_to_precision',
    'parse_decimal',
    'flatten_dict',
    'unflatten_dict',
    'deep_merge',
    'filter_dict',
    'remove_none_values',
    'chunk_list',
    'deduplicate_list',
    'truncate_string',
    'sanitize_filename',
    'generate_hash',
    'safe_json_loads',
    'safe_json_dumps',
    'pretty_json',
    'retry',
    'timer',
    'memoize',
    'get_nested_value',
    'set_nested_value',
    'ensure_list',
]

__version__ = '1.0.0'
